sudo: false

language: python

python:
  - "3.5"
  - "3.6"

env:
  - TWISTED="twisted==17.1.0"
  - TWISTED="twisted"

install:
  - pip install $TWISTED isort unify flake8 -e .[tests]
  - pip freeze

script:
  - pytest
  - flake8
  - isort --check-only --recursive daphne tests
  - unify --check-only --recursive --quote \" daphne tests

